/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';

  static const IconData archive_2 = const IconData(0xea01, fontFamily: _kFontFam);
  static const IconData archive_paper = const IconData(0xea02, fontFamily: _kFontFam);
  static const IconData award_48 = const IconData(0xea03, fontFamily: _kFontFam);
  static const IconData badge_13 = const IconData(0xea04, fontFamily: _kFontFam);
  static const IconData bag_09 = const IconData(0xea05, fontFamily: _kFontFam);
  static const IconData barcode_qr = const IconData(0xea06, fontFamily: _kFontFam);
  static const IconData bear = const IconData(0xea07, fontFamily: _kFontFam);
  static const IconData bell_53 = const IconData(0xea08, fontFamily: _kFontFam);
  static const IconData bookmark = const IconData(0xea09, fontFamily: _kFontFam);
  static const IconData briefcase_24 = const IconData(0xea0a, fontFamily: _kFontFam);
  static const IconData calendar_60 = const IconData(0xea0b, fontFamily: _kFontFam);
  static const IconData camera_20 = const IconData(0xea0c, fontFamily: _kFontFam);
  static const IconData cart_simple = const IconData(0xea0d, fontFamily: _kFontFam);
  static const IconData chat_46 = const IconData(0xea0e, fontFamily: _kFontFam);
  static const IconData check_circle_07 = const IconData(0xea0f, fontFamily: _kFontFam);
  static const IconData cloud_02 = const IconData(0xea10, fontFamily: _kFontFam);
  static const IconData compass_05 = const IconData(0xea11, fontFamily: _kFontFam);
  static const IconData dashboard_level = const IconData(0xea12, fontFamily: _kFontFam);
  static const IconData diamond = const IconData(0xea13, fontFamily: _kFontFam);
  static const IconData edit_78 = const IconData(0xea14, fontFamily: _kFontFam);
  static const IconData email_84 = const IconData(0xea15, fontFamily: _kFontFam);
  static const IconData eye_19 = const IconData(0xea16, fontFamily: _kFontFam);
  static const IconData favourite_31 = const IconData(0xea17, fontFamily: _kFontFam);
  static const IconData flag_points_32 = const IconData(0xea18, fontFamily: _kFontFam);
  static const IconData flash_21 = const IconData(0xea19, fontFamily: _kFontFam);
  static const IconData folder_15 = const IconData(0xea1a, fontFamily: _kFontFam);
  static const IconData gift_2 = const IconData(0xea1b, fontFamily: _kFontFam);
  static const IconData grid_45 = const IconData(0xea1c, fontFamily: _kFontFam);
  static const IconData handout = const IconData(0xea1d, fontFamily: _kFontFam);
  static const IconData heart = const IconData(0xea1e, fontFamily: _kFontFam);
  static const IconData home_52 = const IconData(0xea1f, fontFamily: _kFontFam);
  static const IconData image = const IconData(0xea20, fontFamily: _kFontFam);
  static const IconData key_25 = const IconData(0xea21, fontFamily: _kFontFam);
  static const IconData layers_3 = const IconData(0xea22, fontFamily: _kFontFam);
  static const IconData like_2 = const IconData(0xea23, fontFamily: _kFontFam);
  static const IconData link_72 = const IconData(0xea24, fontFamily: _kFontFam);
  static const IconData lock_open = const IconData(0xea25, fontFamily: _kFontFam);
  static const IconData lock = const IconData(0xea26, fontFamily: _kFontFam);
  static const IconData multiple_11 = const IconData(0xea27, fontFamily: _kFontFam);
  static const IconData notes = const IconData(0xea28, fontFamily: _kFontFam);
  static const IconData pencil = const IconData(0xea29, fontFamily: _kFontFam);
  static const IconData phone_2 = const IconData(0xea2a, fontFamily: _kFontFam);
  static const IconData preferences = const IconData(0xea2b, fontFamily: _kFontFam);
  static const IconData send_2 = const IconData(0xea2c, fontFamily: _kFontFam);
  static const IconData settings_gear_63 = const IconData(0xea2d, fontFamily: _kFontFam);
  static const IconData single_01 = const IconData(0xea2e, fontFamily: _kFontFam);
  static const IconData single_folded_content = const IconData(0xea2f, fontFamily: _kFontFam);
  static const IconData skull_2 = const IconData(0xea30, fontFamily: _kFontFam);
  static const IconData spaceship = const IconData(0xea31, fontFamily: _kFontFam);
  static const IconData square_download = const IconData(0xea32, fontFamily: _kFontFam);
  static const IconData square_upload = const IconData(0xea33, fontFamily: _kFontFam);
  static const IconData support_16 = const IconData(0xea34, fontFamily: _kFontFam);
  static const IconData trash_simple = const IconData(0xea35, fontFamily: _kFontFam);
  static const IconData vector = const IconData(0xea36, fontFamily: _kFontFam);
  static const IconData video_66 = const IconData(0xea37, fontFamily: _kFontFam);
  static const IconData turtle = const IconData(0xea38, fontFamily: _kFontFam);
  static const IconData wallet_43 = const IconData(0xea39, fontFamily: _kFontFam);
  static const IconData widget = const IconData(0xea3a, fontFamily: _kFontFam);
  static const IconData world = const IconData(0xea3b, fontFamily: _kFontFam);
  static const IconData zoom_2 = const IconData(0xea3c, fontFamily: _kFontFam);
}
